// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`

FileInfo getMockFileInfo() =>
    RustLib.instance.api.crateApiTypesGetMockFileInfo();

IndexStatus getMockStatus() =>
    RustLib.instance.api.crateApiTypesGetMockStatus();

String processFileInfo({required FileInfo info}) =>
    RustLib.instance.api.crateApiTypesProcessFileInfo(info: info);

class FileEntry {
  final String path;
  final bool isDir;
  final BigInt sizeBytes;
  final BigInt modifiedMs;

  const FileEntry({
    required this.path,
    required this.isDir,
    required this.sizeBytes,
    required this.modifiedMs,
  });

  @override
  int get hashCode =>
      path.hashCode ^ isDir.hashCode ^ sizeBytes.hashCode ^ modifiedMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileEntry &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          isDir == other.isDir &&
          sizeBytes == other.sizeBytes &&
          modifiedMs == other.modifiedMs;
}

class FileInfo {
  final String name;
  final BigInt sizeBytes;
  final List<String> tags;

  const FileInfo({
    required this.name,
    required this.sizeBytes,
    required this.tags,
  });

  @override
  int get hashCode => name.hashCode ^ sizeBytes.hashCode ^ tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          sizeBytes == other.sizeBytes &&
          tags == other.tags;
}

@freezed
sealed class IndexStatus with _$IndexStatus {
  const IndexStatus._();

  const factory IndexStatus.pending() = IndexStatus_Pending;
  const factory IndexStatus.processing({required double progress}) =
      IndexStatus_Processing;
  const factory IndexStatus.complete({required int chunkCount}) =
      IndexStatus_Complete;
  const factory IndexStatus.failed({required String error}) =
      IndexStatus_Failed;
}
